/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_contentobjects_jnotify_win32_JNotify_win32 */

#ifndef _Included_net_contentobjects_jnotify_win32_JNotify_win32
#define _Included_net_contentobjects_jnotify_win32_JNotify_win32
#ifdef __cplusplus
extern "C" {
#endif
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_FILE_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_FILE_NAME 1L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_DIR_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_DIR_NAME 2L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_ATTRIBUTES
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_ATTRIBUTES 4L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_SIZE
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_SIZE 8L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_LAST_WRITE
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_LAST_WRITE 16L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_LAST_ACCESS
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_LAST_ACCESS 32L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_CREATION
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_CREATION 64L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_SECURITY
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_NOTIFY_CHANGE_SECURITY 256L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ADDED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_ADDED 1L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_REMOVED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_REMOVED 2L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_MODIFIED
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_MODIFIED 3L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_OLD_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_OLD_NAME 4L
#undef net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_NEW_NAME
#define net_contentobjects_jnotify_win32_JNotify_win32_FILE_ACTION_RENAMED_NEW_NAME 5L
/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeInitLogger
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeInitLogger
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeAddWatch
 * Signature: (Ljava/lang/String;JZ)I
 */
JNIEXPORT jint JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeAddWatch
  (JNIEnv *, jclass, jstring, jlong, jboolean);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    getErrorDesc
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_getErrorDesc
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_contentobjects_jnotify_win32_JNotify_win32
 * Method:    nativeRemoveWatch
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_contentobjects_jnotify_win32_JNotify_1win32_nativeRemoveWatch
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
